#!/bin/bash

#interface de Internet
ifinternet="enp0s3"

#interface da rede local
iflocal="enp0s8"

iniciar () {
modprobe iptable_nat
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o $ifinternet -j MASQUERADE

}

parar () {
	iptables -F
	iptables -F -t nat
}

case "$1" in
	"start") iniciar ;;
	"stop")  parar ;;
	"restart")  parar; iniciar ;;
	*) echo "Use o parametro Start ou Stop"
esac

